$(document).ready(function(){
    $(document).on('click','#submit',function(){
       $('.add').show();
    });
    $(document).on('click','#project',function(){
    	$('.add').hide();
    })
      /*$(document).on('click','#get',function(){
       $('.').show();
    });
    $(document).on('click','#imge',function(){
    	$('.details').hide();
    })
     $(document).on('click','#get',function(){
       $('.done').show();
    });
    $(document).on('click','#save',function(){
    	$('.done').hide();
    })*/
});